# Generated by Django 3.0.8 on 2020-10-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=10)),
                ('points', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='Story_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(unique=True)),
                ('question', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Story_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=10000)),
                ('on_chosen', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Levels')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Story_Question')),
            ],
            options={
                'unique_together': {('question', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Aptitude_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=1)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Story_Question')),
            ],
            options={
                'unique_together': {('story', 'question_number')},
            },
        ),
    ]
