# Generated by Django 2.2.7 on 2019-12-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
                ('choice_1', models.CharField(max_length=1000, null=True)),
                ('choice_2', models.CharField(max_length=1000, null=True)),
                ('choice_3', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_1', models.CharField(max_length=10, null=True)),
                ('option_2', models.CharField(max_length=10, null=True)),
                ('option_3', models.CharField(max_length=10, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Story_Question')),
            ],
        ),
    ]
