# Generated by Django 3.0.8 on 2020-10-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_options',
            name='option',
            field=models.TextField(max_length=10000),
        ),
    ]
