# Generated by Django 3.0.2 on 2020-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200222_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levels',
            options={'verbose_name_plural': 'Levels'},
        ),
        migrations.AlterField(
            model_name='story_question',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
