# Generated by Django 3.0.8 on 2020-10-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201016_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story_options',
            options={'ordering': ['pk']},
        ),
    ]
