# Generated by Django 3.0.2 on 2020-02-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200222_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story_answer',
            name='choice_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_1', to='game.Levels'),
        ),
        migrations.AlterField(
            model_name='story_answer',
            name='choice_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_2', to='game.Levels'),
        ),
        migrations.AlterField(
            model_name='story_answer',
            name='choice_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_3', to='game.Levels'),
        ),
    ]
