# Generated by Django 3.0.8 on 2020-11-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20201016_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitude_question',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
