# Generated by Django 3.0.8 on 2020-10-15 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(error_messages={'unique': 'Registration number already Exists'}, unique=True)),
                ('mob_number', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='DPs')),
                ('story', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=0)),
                ('is_story', models.BooleanField(default=True)),
                ('path', models.IntegerField(default=1)),
                ('current_aptitude', models.IntegerField(default=1)),
                ('is_ended', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
