# Generated by Django 3.0.8 on 2020-10-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reg_number',
            field=models.CharField(error_messages={'unique': 'Registration number already Exists'}, max_length=15, unique=True),
        ),
    ]
