# Generated by Django 3.0.8 on 2020-10-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201016_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userid',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
