# Generated by Django 3.0.8 on 2020-10-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_answered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
